CREATE TABLE MYSITE.USER
(
	USERNAME VARCHAR(30) NOT NULL,
	PASSWORD VARCHAR(30) NOT NULL,
	NAME VARCHAR(50),
	PHONE VARCHAR(30),
	ADDRESS VARCHAR(60),
	BANKNAME VARCHAR(50),
	BANKACCOUNT VARCHAR(30),
	PRIMARY KEY (USERNAME)
)


CREATE TABLE MYSITE.TRANSACTION
(
	ID INTEGER not null GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
	S_NAME VARCHAR(50),
	S_ADDRESS VARCHAR(60),
	S_PHONE VARCHAR(30),
	S_BANK_NAME VARCHAR(50),
	S_BANK_ACCOUNT VARCHAR(30),
	CURRENCY VARCHAR(5),
	AMOUNT NUMERIC(15,2),
	R_NAME VARCHAR(50),
	R_ADDRESS VARCHAR(60),
	R_BANK_NAME VARCHAR(50),
	R_BANK_ACCOUNT VARCHAR(30),
	TIME TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
	PRIMARY KEY (ID)
)